### ISSUE TITLE
Some system languages break {attr:level} and {attr:cost} placeholders in skill lore

### ISSUE THREAD

**Issue by bFormat** [Sentropic/SkillAPI-s#22] opened 2021-01-29 13:08 UTC
1.16.5 Paper server

{attr:level} doesn't work.
No matter what level it is, it will continue to be written as 1.

**Comment by Sentropic** [comment] 2021-01-30 20:23
Can you attach you skill file please?

**Comment by Sentropic** [comment] 2021-01-30 21:14
Never mind, I figured it out. It'll be fixed in the next version!
This was a fun one, since it's caused by some system languages using ',' instead of '.' as decimal separator.

**Closed as completed** 2021-02-02 02:20 UTC
Labels: bug
